baseURL: "https://www.nsidr.com/"
languageCode: en-us
title: nsidr
buildFuture: false
taxonomies:
  tag: tags
  series: series
  author: authors
params:
  staticPath: "https://static.nsidr.com/"
  ga: UA-1395930-3
  defaultDescription: "nsidr.com, recalling the bygone exploits of middle-aged Nintendo-likers."
  defaultImage: "https://www.nsidr.com/logo-full.png"
